version: "3"

tasks:
  setup:
    desc: "Setup tools"
    cmds:
      - mise trust -yq
      - mise install

  update:
    desc: "Update tools"
    cmds:
      - mise upgrade

  versions:
    desc: "Show tool versions"
    cmds:
      - mise --version
      - shellcheck --version
      - uv --version
      - yamllint --version
      - markdownlint --version
      - biome --version
      - actionlint --version
      - watchexec --version
