version: "3"

tasks:
  init:
    desc: "Initialize uv project"
    cmds:
      - "[ -f pyproject.toml ] || uv init --bare"

  setup:
    desc: "Setup YAML tools"
    cmds:
      - task: init
      - uv add --dev yamllint

  check:
    desc: "Check YAML"
    cmds:
      - task: lint

  lint:
    desc: "Lint YAML"
    cmds:
      - uv run yamllint .
